### ISSUE TITLE
When I closed the MacBook lid and put the computer into sleep, the timing was inaccurate (verified with an iPhone stopwatch).

### ISSUE THREAD

**Issue by ChinaLiuRixing** [alexkhismatulin/react-use-count-down#10]
When I closed the MacBook lid and put the computer into sleep, the timing was inaccurate (verified with an iPhone stopwatch).

**Comment by alexkhismatulin** [comment]
Yeah, it might be inaccurate in some cases because browsers [can throttle `requestAnimationFrame`](https://mattperry.is/writing-code/browsers-may-throttle-requestanimationframe-to-30fps). I think we could handle that somehow. What do you think should happen in this case?

**Comment by alexkhismatulin** [comment]
@ChinaLiuRixing this should be fixed in `1.0.3`. Re-open the issue if the problem persists.
