### ISSUE TITLE
Support react 18

### ISSUE THREAD

**Issue by jimmi-rbn** [alexkhismatulin/react-use-count-down#38]
Hi.
Do you have plans for supporting react 18 and update the peerDependency?

**Comment by matAlmeida** [comment]
I sent a PR with this change

https://github.com/alexkhismatulin/react-use-count-down/pull/39

**Comment by alexkhismatulin** [comment]
@matAlmeida's update was released to NPM under `1.1.3`. Thank you both guys and sorry for the late response.
