### ISSUE TITLE
Feature to cleanup the countdown

### ISSUE THREAD

**Issue by steviekong** [alexkhismatulin/react-use-count-down#9]
Right now I in my cleanup I just pause the timer. I was wondering if this was enough or there was a cleanup function I could when my component unmounts.

**Comment by alexkhismatulin** [comment]
hey @steviekong 
You can use `reset` to make sure a counter is disposed. It's going to be alright. I think the library should take care of cleanup itself so I'm going to implement that soon

**Comment by alexkhismatulin** [comment]
@steviekong I've added a cleanup effect to the hook so it's going to be done automatically starting from `1.0.2`
